version: 2.1

orbs:
  node: circleci/node@4.0.1

parameters:
  version:
    type: string
    default: 1.2.1

general:
  branches:
    - master

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Grant access to ./gradlew.
          command: |
            chmod +x gradlew

      - run:
          name: Set up the workspace for ci build
          command: |
            ./gradlew setupCiWorkspace

      - run:
          name: Attempt to build the mod.
          command: |
            ./gradlew clean build --refresh-dependencies

      - store_artifacts:
          path: ./build/libs

      - node/install:
          install-yarn: true

      - run:
          name: Discord webhook
          command: |
            cd .circleci/discordwebhook
            yarn install
            yarn start << pipeline.git.branch >> << pipeline.parameters.version >> $CIRCLE_BUILD_NUM https://github.com/linustouchtips/momentum/compare/<< pipeline.git.base_revision >>...<< pipeline.git.revision >>